export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'
export const EMPTY_TO_CART = 'EMPTY_TO_CART'
export const INCRIMENT_TO_CART = 'INCRIMENT_TO_CART'
export const DECREMENT_TO_CART = 'DECREMENT_TO_CART'
export const ADD_TO_WHISHLIST = 'ADD_TO_WHISHLIST'
export const REMOVE_TO_WHISHLIST = 'REMOVE_TO_WHISHLIST'
export const EMPTY_WHISHLIST = 'EMPTY_WHISHLIST'
export const WHISHLIST_TO_CART = 'WHISHLIST_TO_CART'
export const PRODUCT_LIST = 'PRODUCT_LIST'
export const PRODUCT_SET = 'PRODUCT_SET'






